/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Предстоящие встречи одним списком по всем типам событий,
         *     по возрастанию времени начала. Прошедшие встречи не возвращаются.
         */
        get: operations["AdminBookings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Все типы событий владельца. */
        get: operations["AdminEventTypes_list"];
        put?: never;
        /** @description Создать тип события. */
        post: operations["AdminEventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Записаться на свободный слот. */
        post: operations["PublicBookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список видов брони на публичной странице. */
        get: operations["PublicEventTypes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Один тип события — для прямой ссылки на страницу бронирования. */
        get: operations["PublicEventTypes_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Свободные слоты выбранного типа события на 14 дней вперёд,
         *     по возрастанию времени. Занятые интервалы уже исключены.
         */
        get: operations["PublicEventTypes_slots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Запись гостя на звонок. */
        Booking: {
            /** @description Непрозрачный идентификатор (UUID). */
            id: string;
            eventTypeId: string;
            /** @description Название типа события на момент чтения — чтобы список владельца не требовал второго запроса. */
            eventTypeTitle: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
            /** @description Необязательный комментарий гостя. */
            notes?: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Тело запроса на создание брони. */
        BookingCreate: {
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало выбранного слота; должно совпадать со `start` одного из свободных слотов.
             *     Часовой пояс обязателен: `2026-08-20T09:00:00Z` либо смещение `2026-08-20T12:00:00+03:00`.
             *     Строка без пояса — не момент времени, и сервер отвечает на неё `400 validation_failed`.
             */
            start: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
            notes?: string;
        };
        /** @description Тип встречи, который публикует владелец календаря. */
        EventType: {
            /** @description Непрозрачный идентификатор (UUID). */
            id: string;
            /** @description Название, которое видит гость в списке видов брони. */
            title: string;
            /** @description Описание встречи для страницы бронирования. */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах; кратна 30.
             */
            durationMinutes: number;
        };
        /** @description Тело запроса на создание типа события. */
        EventTypeCreate: {
            title: string;
            description: string;
            /**
             * Format: int32
             * @description Кратна 30: 30, 60, 90, 120.
             */
            durationMinutes: number;
        };
        /** @description Типа события с таким `id` не существует. */
        EventTypeNotFound: {
            /** @enum {string} */
            error: "event_type_not_found";
            message: string;
        };
        /**
         * @description Свободный интервал под конкретный тип события.
         *     Слоты не хранятся — они вычисляются на лету из окна записи и существующих броней.
         */
        Slot: {
            /**
             * Format: date-time
             * @description Начало встречи, всегда попадает на сетку с шагом 30 минут.
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец встречи: `start + durationMinutes` типа события.
             */
            end: string;
        };
        /**
         * @description Слот уже занят: запрошенный интервал пересекается с существующей бронью
         *     (в том числе бронью другого типа события).
         */
        SlotUnavailable: {
            /** @enum {string} */
            error: "slot_unavailable";
            message: string;
        };
        /** @description Тело запроса не прошло валидацию: не те типы, не та сетка, время вне окна записи. */
        ValidationError: {
            /** @enum {string} */
            error: "validation_failed";
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminBookings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    AdminEventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    AdminEventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Тело запроса не прошло валидацию: не те типы, не та сетка, время вне окна записи. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    PublicBookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Тело запроса не прошло валидацию: не те типы, не та сетка, время вне окна записи. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Типа события с таким `id` не существует. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeNotFound"];
                };
            };
            /**
             * @description Слот уже занят: запрошенный интервал пересекается с существующей бронью
             *     (в том числе бронью другого типа события).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotUnavailable"];
                };
            };
        };
    };
    PublicEventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    PublicEventTypes_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Типа события с таким `id` не существует. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeNotFound"];
                };
            };
        };
    };
    PublicEventTypes_slots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description Типа события с таким `id` не существует. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeNotFound"];
                };
            };
        };
    };
}
